### PR TITLE
chore(ui): move templates folder

### PR DESCRIPTION
**Pull request by WendyTP**
# Checklist:
- [x] The code follows our code [conventions](https://github.com/my-cloud/ruthenium/blob/main/.github/CONTRIBUTING.md#go).
- [x] Important principle changes have been documented in the [wiki](https://github.com/my-cloud/ruthenium/wiki).
- [x] The new code is covered by unit tests with assertions.
- [x] The behaviour [node](https://github.com/my-cloud/ruthenium/blob/main/src/node) and [UI](https://github.com/my-cloud/ruthenium/blob/main/src/ui) have been manually tested and is as expected.
- [x] The squash commit message follows our [conventions](https://github.com/my-cloud/ruthenium/blob/main/.github/CONTRIBUTING.md#git).

### CODE REVIEW

**Comment by WendyTP** [comment]
@JeremyPansier : Can you please check this pull request?

**Comment by JeremyPansier** [comment]
> @JeremyPansier : Can you please check this pull request?

Sure! Thank you so much for contributing to Ruthenium!

**Comment by JeremyPansier** [comment]
* [ ] The behaviour [node](https://github.com/my-cloud/ruthenium/blob/main/src/node) and [UI](https://github.com/my-cloud/ruthenium/blob/main/src/ui) have been manually tested and is as expected. &rarr; did you test the docker image?
 * [ ] The squash commit message follows our [conventions](https://github.com/my-cloud/ruthenium/blob/main/.github/CONTRIBUTING.md#git). &rarr; please rename this PR to `chore(ui): move templates folder` to be sure that the suggested squash commit message will be `chore(ui): move templates folder (#175)`

**Comment by WendyTP** [comment]
The container has been built and tested. The pull request title is also changed.

**Comment by WendyTP** [comment]
By the way, the README file contains misleading docker run parameters.
https://github.com/my-cloud/ruthenium/blob/main/README.md?plain=1#L51-L55

**Comment by JeremyPansier** [comment]
> By the way, the README file contains misleading docker run parameters. https://github.com/my-cloud/ruthenium/blob/main/README.md?plain=1#L51-L55

You are right, the `-host-ip` parameter for the node docker image is obsolete. I just created [this issue](#175) to fix it.

**Review by JeremyPansier — APPROVED** [review]
Thank you so much for this nice issue resolution, and thank you for having thought of updating the README.md. You are free to merge it now.

**Pull request merged**
